### ISSUE TITLE
Failed to update bot's status: sending the message over the websocket failed

### ISSUE THREAD

**Issue by Zokalyx** [Cldfire/mc-server-wrapper#5]
Hi, I can't get this software to connect to Discord.
I have tried:
 - using different bots
 - using different channels
 - building from source

 but I always get this error, specifically just after world loading finishes:
```
Failed to update bot's status: sending the message over the websocket failed
```
Could this be related to Discord possibly having updated their API?

**Comment by Zokalyx** [comment]
I'm terribly sorry for possibly wasting your time; I didn't have the `SERVER MEMBERS INTENT` enabled.

**Comment by Cldfire** [comment]
Oh please don't be sorry! Having a better error message here / helping the user understand that they need to enable an intent in their bot's admin panel would be awesome, when I have time I'll look into what we can do there. I'll open a new issue for that.

Please feel free to file issues for anything you run into! 🙂
