### ISSUE TITLE
Tech Newbie

### ISSUE THREAD

**Issue by catgirl86** [Cldfire/mc-server-wrapper#9]
Could someone give beginner-friendly instructions for how to make the Discord chat bridge work? I'm familiar with Discord, how to make a bot, etc. But I don't know what files from GitHub to download, what to run, what to upload to my 3rd-party server's file manager. Thanks!

**Comment by Cldfire** [comment]
Hiya! Thanks for stopping by, it's cool to see people interested in using mc-server-wrapper. However:

> what to upload to my 3rd-party server's file manager

Depending on what server hosting solution you're using you may not be able to use my program. Typically these services manage Minecraft servers for you in a way that doesn't allow for programs like mine to be run on top of the Minecraft server. In these cases you'd want to use something like https://essentialsx.net/wiki/Discord-Tutorial.html to get a Discord bridge working with your server (assuming your server host allows running modded server software such as [Spigot](https://www.spigotmc.org)).

If you link the hosting service you're using I'd be happy to take a peek and see what their policies are :)

**Comment by catgirl86** [comment]
I'm using PebbleHost, Vanilla 1.19 server.

**Comment by Cldfire** [comment]
Gotcha. Yeah, you won't be able to run mc-server-wrapper there. First, download a copy of your server files so if something gets messed up you can put things back the way they were. Then, the best way for you to get started with a Discord chat bridge would be to go here in your management dashboard:

<img width="1176" alt="Screen Shot 2022-06-11 at 12 07 53 AM" src="https://user-images.githubusercontent.com/13814214/173171962-9de02946-5cb7-46fe-af75-5dc9c660cf90.png">

Click on "JAR & Preinstall Menu", and then click on "Spigot" on the left:

<img width="250" alt="Screen Shot 2022-06-11 at 12 10 41 AM" src="https://user-images.githubusercontent.com/13814214/173172023-2f468182-ebb2-4f98-834a-ee45ed749e6c.png">

Choose Spigot 1.19:

<img width="344" alt="Screen Shot 2022-06-11 at 12 17 45 AM" src="https://user-images.githubusercontent.com/13814214/173172206-c2a8d4bd-77d2-4665-b088-fc39c813691c.png">

and save that. (It should be able to import your existing vanilla world without issue.)

Then you can install the [EssentialsX plugin](https://www.spigotmc.org/resources/essentialsx.9089/) for Spigot (basic installation instructions [here](https://essentialsx.net/wiki/Installing-EssentialsX.html)). One of its modules is EssentialsX Discord; make sure you install that one and then you can view the setup instructions for it [here](https://essentialsx.net/wiki/Discord-Tutorial.html). That'll get you a great Discord chat bridge for your server 😄. There's also a bunch of other stuff EssentialsX can do if you want to play around with it; my friends and I play mostly vanilla settings, but we like having homes that we can set and teleport back to + the ability to request to teleport to each other. It makes exploring easier ✨. Or you can leave that all off.

If you have any questions let me know!

**Comment by catgirl86** [comment]
Thank you for the help!
